import type { Enhancement } from "@/components/EnhancementCard";
import type { CategoryId } from "@/components/CategoryTabs";

export const ENHANCEMENTS: Record<CategoryId, Enhancement[]> = {
  "camera-angles": [
    { id: "ca-1", title: "Wide Establishing Shot", description: "Eye-level wide angle capturing the full scene context", category: "camera-angles" },
    { id: "ca-2", title: "Dutch Angle", description: "Tilted camera creating dynamic tension and unease", category: "camera-angles" },
    { id: "ca-3", title: "Bird's Eye View", description: "Overhead shot looking directly down on the subject", category: "camera-angles" },
    { id: "ca-4", title: "Low Angle", description: "Camera positioned below subject looking up, emphasizing power", category: "camera-angles" },
    { id: "ca-5", title: "Over-the-Shoulder", description: "Framed from behind one subject viewing another", category: "camera-angles" },
    { id: "ca-6", title: "Close-Up", description: "Tight framing on subject's face or detail, intimate and emotional", category: "camera-angles" },
    { id: "ca-7", title: "Extreme Close-Up", description: "Very tight shot on specific detail like eyes or hands", category: "camera-angles" },
    { id: "ca-8", title: "Medium Shot", description: "Waist-up framing balancing subject and environment", category: "camera-angles" },
  ],
  "camera-motion": [
    { id: "cm-1", title: "Slow Dolly In", description: "Smooth forward camera movement creating intimacy", category: "camera-motion" },
    { id: "cm-2", title: "Tracking Shot", description: "Camera following subject's lateral movement fluidly", category: "camera-motion" },
    { id: "cm-3", title: "Handheld", description: "Natural camera shake for documentary realism and energy", category: "camera-motion" },
    { id: "cm-4", title: "Crane Shot", description: "Sweeping vertical or arcing movement for grandeur", category: "camera-motion" },
    { id: "cm-5", title: "Slow Pan", description: "Horizontal rotation revealing the environment gradually", category: "camera-motion" },
    { id: "cm-6", title: "Tilt Up/Down", description: "Vertical rotation from ground to sky or vice versa", category: "camera-motion" },
    { id: "cm-7", title: "Steadicam Glide", description: "Smooth floating movement through space", category: "camera-motion" },
    { id: "cm-8", title: "Static/Locked", description: "Fixed camera position allowing action to unfold", category: "camera-motion" },
  ],
  "lighting": [
    { id: "l-1", title: "Golden Hour", description: "Warm, soft natural light during sunrise or sunset", category: "lighting" },
    { id: "l-2", title: "Hard Side Light", description: "Strong directional light creating dramatic shadows", category: "lighting" },
    { id: "l-3", title: "Soft Diffused", description: "Even, wraparound lighting with minimal shadows", category: "lighting" },
    { id: "l-4", title: "Backlighting", description: "Light from behind subject creating silhouette or rim light", category: "lighting" },
    { id: "l-5", title: "Volumetric Rays", description: "Visible light beams cutting through atmosphere or fog", category: "lighting" },
    { id: "l-6", title: "Neon Glow", description: "Colorful artificial lighting with electric atmosphere", category: "lighting" },
    { id: "l-7", title: "Candlelit Ambience", description: "Warm, flickering practical light sources", category: "lighting" },
    { id: "l-8", title: "Blue Hour", description: "Cool twilight tones with deep blue sky", category: "lighting" },
  ],
  "style": [
    { id: "s-1", title: "Cinematic Anamorphic", description: "2.39:1 widescreen with characteristic lens flares", category: "style" },
    { id: "s-2", title: "1970s Film Stock", description: "Grainy, warm tones with vintage color science", category: "style" },
    { id: "s-3", title: "IMAX Documentary", description: "Crystal-clear, ultra-sharp large-format aesthetic", category: "style" },
    { id: "s-4", title: "Black & White Film Noir", description: "High contrast monochrome with deep shadows", category: "style" },
    { id: "s-5", title: "Wes Anderson Symmetry", description: "Perfectly centered, pastel-colored compositions", category: "style" },
    { id: "s-6", title: "Blade Runner Cyberpunk", description: "Neon-soaked, rain-slicked dystopian atmosphere", category: "style" },
    { id: "s-7", title: "16mm Documentary", description: "Raw, authentic handheld with natural grain", category: "style" },
    { id: "s-8", title: "Music Video Energy", description: "Dynamic cuts, color grading, stylized visuals", category: "style" },
  ],
  "depth-of-field": [
    { id: "dof-1", title: "Shallow Focus", description: "Subject sharp, background beautifully blurred (bokeh)", category: "depth-of-field" },
    { id: "dof-2", title: "Deep Focus", description: "Everything from foreground to background in crisp focus", category: "depth-of-field" },
    { id: "dof-3", title: "Rack Focus", description: "Focus shifts from one subject to another during shot", category: "depth-of-field" },
    { id: "dof-4", title: "Selective Focus", description: "Isolating specific element while rest falls soft", category: "depth-of-field" },
    { id: "dof-5", title: "Tilt-Shift Miniature", description: "Narrow plane of focus creating toy-like effect", category: "depth-of-field" },
    { id: "dof-6", title: "Hyperfocal Distance", description: "Maximum depth with acceptable sharpness throughout", category: "depth-of-field" },
  ],
  "motion-timing": [
    { id: "mt-1", title: "Slow Motion", description: "Action slowed to 1/4 speed for dramatic effect", category: "motion-timing" },
    { id: "mt-2", title: "Time-lapse", description: "Hours compressed into seconds showing passage of time", category: "motion-timing" },
    { id: "mt-3", title: "Beat-Perfect Timing", description: "Actions synchronized to counted beats (3 steps, pause, turn)", category: "motion-timing" },
    { id: "mt-4", title: "Held Moment", description: "Subject freezes mid-action for 2 seconds before continuing", category: "motion-timing" },
    { id: "mt-5", title: "Gradual Reveal", description: "Subject or object slowly enters frame over 4 seconds", category: "motion-timing" },
    { id: "mt-6", title: "Quick Cut Energy", description: "Fast-paced action completing in under 2 seconds", category: "motion-timing" },
  ],
  "color-palette": [
    { id: "cp-1", title: "Warm Earth Tones", description: "Amber, terracotta, burnt sienna, cream palette", category: "color-palette" },
    { id: "cp-2", title: "Cool Blue-Teal", description: "Icy blues, teals, silver creating cold atmosphere", category: "color-palette" },
    { id: "cp-3", title: "Complementary Orange-Teal", description: "Classic cinematic color scheme with high contrast", category: "color-palette" },
    { id: "cp-4", title: "Monochromatic Green", description: "Various shades of single color for cohesive mood", category: "color-palette" },
    { id: "cp-5", title: "Pastel Dream", description: "Soft pinks, lavenders, mint greens, peachy tones", category: "color-palette" },
    { id: "cp-6", title: "Neon Synthwave", description: "Electric purples, hot pinks, cyan creating retro-future vibe", category: "color-palette" },
    { id: "cp-7", title: "Desaturated Bleach", description: "Washed-out colors with blown highlights", category: "color-palette" },
    { id: "cp-8", title: "Rich Jewel Tones", description: "Deep emerald, sapphire, ruby, gold for opulence", category: "color-palette" },
  ],
};
